### ISSUE TITLE
Editor crashes when creating a new soft class reference variable in a blueprint.

### ISSUE THREAD

**Issue by redhadesmtl** [DoubleDeez/MDMetaDataEditor#7]
REPRODUCTION STEPS
- Enable the MDMetaDataEditor plugin in Unreal Editor's plugins window,
- Create a new blueprint derived from Object and open it.
- Add a new variable to the blueprint.
- Set the new variable type to Object and Soft Class Reference.

RESULT
- The Unreal Editor crashes

NOTES
- Disabling the MDMetaDataEditor plugin in Unreal Editor's plugins window and reopening the project will stop Unreal Editor from crashing when creating a new variable of type Object and Soft Class Reference.

![2024-01-21 16_45_09-Clipboard](https://github.com/DoubleDeez/MDMetaDataEditor/assets/57854932/a8c1157f-6199-4cf6-a350-8b8d10897df8)

**Comment by DoubleDeez** [comment]
Which commit are you on? I'd expect this change to fix that crash https://github.com/DoubleDeez/MDMetaDataEditor/commit/e7af8f8a568cd2f88b01ef431df3edaad23ccab7

**Comment by redhadesmtl** [comment]
Sorry, I double checked and I had not updated the plugin in the right project folder. (facepalm)
My bad.
You are right, this is fixed already.
